# Generated by Django 4.1.3 on 2022-12-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Briefing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='widgets',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
